### PR TITLE
display pictures in tweets https://github.com/chrissimpkins/tweetledle/issues/51

### PR DESCRIPTION
**Pull request by vinhdizzo**

### CODE REVIEW

**Comment by chrissimpkins** [comment]
This is great.  I will take a look at it tomorrow.  Do you mind pushing images from your feed reader with a series of tweets that include and do not include images? I am curious how it renders them.  

Thanks much for the contribution.  I will update the contributors list once I get this merged.

**Comment by vinhdizzo** [comment]
Here it is with and without images in Tiny Tiny RSS:
with_image
without_image

**Comment by chrissimpkins** [comment]
Looks great! Thanks for pushing the screenshots.

@levymetal Christian, I need some PHP advice.  We are trying to add inline images to the RSS feeds here and I wanted to see if you think that this is there is a response time benefit to altering the if block here:

https://github.com/vinhdizzo/tweetledee/blob/master/tweetledee/favoritesrss.php#L181-L183

so that it tests for the presence of a local variable set from this object property rather than testing to see if the object property itself is set?

Thanks much for your input.

**Comment by levymetal** [comment]
Hey Chris,

My gut instinct is that there wouldn't be any noticeable difference in performance. Apparently `isset` can perform 100,000k operations in 0.2 seconds, so if there's a bottleneck, this probably isn't it. However, because you re-use the same conditional below, I think it would be a good idea to move the condition into a variable if only for readability.

A small refactor would be to modify the condition to check if the media property is empty. If media exists, you can safely assume that the media_url property exists as well, so there's no need to check for its existence.

This *should* work (untested though):

```php
$hasMedia = ! empty( $currentitem['entities']['media'] );

if ( $hasMedia ) {
  $picurl = $currentitem['entities']['media'][0]['media_url'];
}
```

**Comment by chrissimpkins** [comment]
@levymetal thank you very much! I really appreciate the feedback. I will give this a shot.

**Comment by chrissimpkins** [comment]
@vinhdizzo will try to merge this with Christian's refactor over the weekend.  You willing to test it once we refactor with the `$hasMedia` variable?

**Comment by vinhdizzo** [comment]
Yes I could test `homerss.php`.

**Comment by chrissimpkins** [comment]
:+1:

**Pull request merged**
